(define (problem door)
 (:domain door)
 (:objects  knight evil_knight princess - character
            bedroom armory hallway cell - place)
 
 (:init (at knight cell)
        (at evil_knight gatehouse)
        (at princess bedroom)
        (has princess key)
        (in armory axe)
        (adjacent hallway cell)
        (adjacent hallway gatehouse)
        (adjacent hallway bedroom)
        (adjacent gatehouse armory)
        (intends knight (doorOpen))
        (intends evil_knight (and (not (doorOpen)) 
                                  (has evil_knight key) 
                                  (has evil_knight axe)))
        (intends princess (has knight key))
        (intends princess (has knight axe))
 )
 
 (:goal (and (doorOpen)
             (or (has evil_knight key)
                 (has evil_knight axe))
             (at evil_knight gatehouse))
 )
)